name: TravelGuyd
favicon: null
layout_spectrum: 0.5052148893009871
typography_spectrum: 0.7311257994733751
title: The Travel Guyd
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#171717'
    - '#6c6060'
    - '#f84817'
    - '#ada6a0'
    - '#fdfeff'
  brandStrength: 0.9857505310792476
  lightness: 0.7823678753338754
  saturation: 0.4102458341512829
  rhythmicContrast: 0.397425283677876
purpose: []
